# -*- coding: utf-8 -*-
"""chatbot_LokAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZtZAB2-NQKfIpTdnTL9Qfw5H_qbPG_Q
"""

from google.colab import drive
drive.mount("/content/drive")

import os
os.chdir("/content/drive/MyDrive/LockAI_Project")

!pip install fastapi uvicorn nest-asyncio pyngrok requests
!pip install fastapi uvicorn nest-asyncio pyngrok openai langdetect deep-translator

import os
import signal
import subprocess

# Kill any process using port 8000
result = subprocess.run(['fuser', '-k', '8000/tcp'], capture_output=True)
print("Killed port 8000:", result)

# Also kill all ngrok tunnels
from pyngrok import ngrok
ngrok.kill()
print("Killed ngrok")

SARVAM_API_KEY = "sk_nisznd9t_ipWfE1Y8D5HvaHAAMFgqkspk"

from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
import uvicorn
import requests

nest_asyncio.apply()

app = FastAPI()

class ChatRequest(BaseModel):
    message: str

def detect_language(text):
    url = "https://api.sarvam.ai/v1/language-detection"

    headers = {
        "Authorization": f"Bearer {SARVAM_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "input": text
    }

    res = requests.post(url, json=payload, headers=headers)
    data = res.json()
    print("RAW LANGUAGE DETECTION RESPONSE:", data)
    return data.get("language_code", "en")

def translate_text(text, source_lang, target_lang):
    if source_lang == target_lang:
        return text

    url = "https://api.sarvam.ai/v1/translate"

    headers = {
        "Authorization": f"Bearer {SARVAM_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "input": text,
        "source_language_code": source_lang,
        "target_language_code": target_lang
    }

    res = requests.post(url, json=payload, headers=headers)
    data = res.json()
    print("TRANSLATION API RESPONSE:", data)
    return data.get("translated_text", text)

# def detect_intent(text):
#     url = "https://api.sarvam.ai/v1/chat/completions"

#     headers = {
#         "Authorization": f"Bearer {SARVAM_API_KEY}",
#         "Content-Type": "application/json"
#     }

#     payload = {
#         "model": "sarvam-m",
#         "messages": [
#             {
#                 "role": "system",
#                 "content": "Classify intent into: general_query or issue_status. Only return one word."
#             },
#             {
#                 "role": "user",
#                 "content": text
#             }
#         ]
#     }

#     res = requests.post(url, json=payload, headers=headers)
#     data = res.json()

#     return data["choices"][0]["message"]["content"].strip()

import re
import requests
import ast

# 🧠 FINAL SYSTEM PROMPT
SYSTEM_PROMPT = """
You are LokAI Assistant.

STRICT RULES:
- Answer in maximum 2–3 lines ONLY
- Be direct, practical, and helpful
- No explanations, no reasoning
- No step numbering, no bullets
- No quotes, no \\n, no symbols

APP CONTEXT:
- User is already inside the app
- Submit issue → "Submit Issue"
- Track issue → "My Issues"

YOUR JOB:
1. Answer general app queries clearly
2. Help user navigate inside app
3. Give small practical civic advice when relevant

ADVICE RULES:
- Give only simple, safe, real-world suggestions
- Do NOT give technical or risky instructions
- Keep advice short (1 line max)

EXAMPLES:

User: how to report issue
Answer: Go to Submit Issue, fill details and submit your complaint.

User: garbage problem in my area
Answer: Report it from Submit Issue with a clear photo and exact location for faster action.

User: how to check status
Answer: Open My Issues section to track your complaint updates.

User: water leakage problem
Answer: Report it with proper location and description so authorities can act quickly.

STYLE:
- Simple
- Clear
- Human-like
- No extra text

"""

# ✅ REMOVE <think> TAGS
def clean_response(text):
    try:
        text = ast.literal_eval(text)
    except:
        pass

    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)

    text = text.replace('\"', '')

    text = text.replace('\n', ' ')

    text = re.sub(r"\b\d+\.\s*", "", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

# ✅ LIMIT TO 3 LINES (extra safety)
def limit_lines(text, max_lines=3):
    lines = text.split("\n")
    return "\n".join(lines[:max_lines])

# ✅ MAIN SARVAM RESPONSE FUNCTION
def generate_response(text):
    url = "https://api.sarvam.ai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {SARVAM_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "sarvam-m",
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text}
        ]
    }

    res = requests.post(url, json=payload, headers=headers)
    data = res.json()

    raw_output = data["choices"][0]["message"]["content"]

    # ✅ CLEAN + LIMIT OUTPUT
    cleaned = clean_response(raw_output)
    final = limit_lines(cleaned)

    return final

!ngrok config add-authtoken 3BFYhMYMKAe5tIeJiLAaqV8B6zu_3vRCN8sMgzuYQi68ktQ3Z

"""from here the phase 2 --- complaint status"""

!pip install motor pymongo

import os

MONGODB_URL = "mongodb+srv://harsh:Amandixit123@cluster0.hwzu3ic.mongodb.net/?retryWrites=true&w=majority"

os.environ["MONGODB_URL"] = MONGODB_URL

from pymongo import MongoClient
from bson.objectid import ObjectId

# Sync client - no event loop issues
client = MongoClient(os.getenv("MONGODB_URL"))
db = client["lokai_db"]

# Test connection
print("Connected to MongoDB ✅")
print("Collections:", db.list_collection_names())

def show_issues():
    cursor = db.issues.find().limit(5)
    for issue in cursor:
        print("ObjectId:", issue["_id"])
        print(issue)
        print("-" * 40)

show_issues()

from bson import ObjectId

def test_fetch():
    issue_id = input("Enter ObjectId: ")

    try:
        issue = db.issues.find_one({"_id": ObjectId(str(issue_id))})

        if issue:
            print("Issue Found:", issue)
        else:
            print("No issue found")

    except Exception as e:
        print("ERROR:", e)

test_fetch()

def format_issue_status(issue):
    status = issue.get("status", "").upper()

    if status == "OPEN":
        return "Your issue is registered and awaiting action."

    elif status == "IN_PROGRESS":
        return "Your issue is currently being worked on."

    elif status == "RESOLVED_L1":
        return "Your issue has been resolved by the authority."

    elif status == "CLOSED":
        return "Your issue has been successfully closed."

    else:
        return "Your issue status is currently unavailable."

import re

def clean_intent(text):
    # Remove <think>
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)

    # Remove spaces/newlines
    text = text.strip().lower()

    return text


def detect_intent(text):
    url = "https://api.sarvam.ai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {SARVAM_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "sarvam-m",
        "messages": [
            {
                "role": "system",
                "content": """You are an intent classifier. Classify the user message into ONLY one of these two intents:

issue_status → ONLY when the user is explicitly asking about the status/update of an already submitted complaint AND provides a complaint ID (a long code like 69ba2ed5ed8e612d6434aa64).

general_query → Everything else. This includes:
- Reporting a new problem (pothole, garbage, fire, water, etc.)
- Asking how to use the app
- Asking for advice or help
- Any civic complaint or emergency without an ID

RULE: If there is NO complaint ID in the message, ALWAYS return general_query.

Return ONLY one word: general_query or issue_status. No explanation."""
            },
            {
                "role": "user",
                "content": text
            }
        ]
    }

    res = requests.post(url, json=payload, headers=headers)
    data = res.json()

    raw = data["choices"][0]["message"]["content"]

    return clean_intent(raw)

import re

def extract_object_id(text):
    # Normalize text
    text = text.lower()

    # Find all 24-length hex strings
    matches = re.findall(r"[a-f0-9]{24}", text)

    if matches:
        return matches[0]

    return None

@app.post("/chat")
async def chat(req: ChatRequest):
    user_msg = req.message

    lang = detect_language(user_msg)
    print("DETECTED LANGUAGE:", lang)
    english_msg = translate_text(user_msg, lang, "en")

    print("USER MSG:", user_msg)
    print("ENGLISH MSG:", english_msg)

    intent = detect_intent(english_msg)
    print("INTENT:", intent)

    if "issue_status" in intent.lower():

        match = re.findall(r"[a-fA-F0-9]{24}", user_msg)
        print("RAW MATCHES:", match)
        issue_id = match[0] if match else None
        print("FINAL EXTRACTED ID:", issue_id)

        if not issue_id:
            response_text = "Please provide a valid issue ID."
        else:
            try:
                # ✅ No await - sync call
                issue = db.issues.find_one({"_id": ObjectId(issue_id)})
                print("Query result:", issue)

                if issue:
                    response_text = format_issue_status(issue)
                else:
                    response_text = "Issue not found in database."

            except Exception as e:
                import traceback
                print("FULL TRACEBACK:\n", traceback.format_exc())
                response_text = f"Error: {str(e)}"
    else:
        response_text = generate_response(english_msg)
    print("RESPONSE BEFORE TRANSLATION:", response_text)   # ← ADD THIS LINE
    print("TRANSLATING TO:", lang)

    final_response = translate_text(response_text, "en", lang)
    print("FINAL RESPONSE:", final_response)
    return {
        "intent": intent,
        "response": final_response
    }

from pyngrok import ngrok
import uvicorn
import threading
import time

# Kill old
ngrok.kill()
time.sleep(2)  # wait for port to free up

# Fresh tunnel
public_url = ngrok.connect(8000)
print("Public URL:", public_url)

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="debug")

t = threading.Thread(target=run, daemon=True)
t.start()
time.sleep(2)
print("Server started ✅")